# Hexapod Warm-Up

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from lsst.sitcom import vandv

exec_info = vandv.ExecutionInfo()
print(exec_info)


Executed by isotuela on 2022-08-17T17:05:39.284.
  Running in yagan09 at summit



---
## Setup Notebook for Test

- Import all libraries
- Get the remotes ready

In [3]:
import asyncio
import logging
import os
import time
import yaml

import astropy.units as u
import numpy as np
import pandas as pd

from astropy.time import Time
from datetime import datetime, timedelta
from matplotlib import pyplot as plt

from lsst.ts.observatory.control.maintel import MTCS, ComCam
from lsst_efd_client import EfdClient
from lsst.ts import salobj

Setting up logger

In [4]:
logging.basicConfig(format="%(name)s:%(message)s", level=logging.DEBUG)

In [5]:
logger = logging.getLogger("setup")
logger.level = logging.DEBUG

Instantiate script for logging into EFD and start script task

In [6]:
logger.info(f'Your UID is {os.getuid()}')
index = os.getuid() * 10 + np.random.randint(0, 9)

logger.info(f'The generated index is {index}')

In [7]:
test_message = "Hexapod Warm-Up"
script = salobj.Controller("Script", index=index)
await script.start_task

Create EFD client

In [8]:
client = vandv.efd.create_efd_client()

Make sure DDS Daemon is running and startup Domain

In [9]:
domain = salobj.Domain()

Create the remote for the Hexapod

In [10]:
mtcs = MTCS(domain=domain, log=logger)

In [11]:
await mtcs.start_task

[None, None, None, None, None, None, None, None, None, None]

In [12]:
vandv.logger.add_filter_to_mtcs()

## Helper Functions

In [13]:
z = mtcs.rem.mthexapod_1.tel_application.get().position[2]
print(f'z position is {z} um')

z position is 0.08202382491720897 um


In [14]:
async def moveHexInSteps(start_z, end_z, step_size, time_sleep=15):
   
    if start_z > end_z:
        step_size = -step_size
        
    print(f'Step size is {step_size} um, \n z positions \n {np.arange(start_z,end_z+step_size, step_size)}')
   
    for z in np.arange(start_z, end_z+, step_size):
        logger.info(f"Moving z to {z:.2f} um")
        await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=z,u=0,v=0,w=0,sync=True)

        time.sleep(time_sleep)

---
# Step size 200 um

In [ ]:
step = 200
start = 10000
end = -10000

In [ ]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [ ]:
await moveHexInSteps(0, start, step)

In [ ]:
await moveHexInSteps(start, end, step)

In [ ]:
await moveHexInSteps(end, 0, step)

In [ ]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

---
## Step size 500 um

In [15]:
step = 500
start = 10000
end = -10000

In [16]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [17]:
await moveHexInSteps(0, start, step)

Step size is 500 um, 
 z positions 
 [    0   500  1000  1500  2000  2500  3000  3500  4000  4500  5000  5500
  6000  6500  7000  7500  8000  8500  9000  9500 10000]


In [18]:
await moveHexInSteps(start, end, step)

Step size is -500 um, 
 z positions 
 [ 10000   9500   9000   8500   8000   7500   7000   6500   6000   5500
   5000   4500   4000   3500   3000   2500   2000   1500   1000    500
      0   -500  -1000  -1500  -2000  -2500  -3000  -3500  -4000  -4500
  -5000  -5500  -6000  -6500  -7000  -7500  -8000  -8500  -9000  -9500
 -10000]


In [19]:
await moveHexInSteps(end, 0, step)

Step size is 500 um, 
 z positions 
 [-10000  -9500  -9000  -8500  -8000  -7500  -7000  -6500  -6000  -5500
  -5000  -4500  -4000  -3500  -3000  -2500  -2000  -1500  -1000   -500
      0]


In [20]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

---
## Step size 1000 um

In [30]:
step = 1000
start = 10000
end = -10000

In [31]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [32]:
await moveHexInSteps(0, start, step)

Step size is 1000 um, 
 z positions 
 [    0  1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]


In [ ]:
await moveHexInSteps(start, end, step)

Step size is -1000 um, 
 z positions 
 [ 10000   9000   8000   7000   6000   5000   4000   3000   2000   1000
      0  -1000  -2000  -3000  -4000  -5000  -6000  -7000  -8000  -9000
 -10000]


In [4]:
await moveHexInSteps(5000, 0, step)

NameError: name 'moveHexInSteps' is not defined

In [ ]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

---
## Step size 2000 um

In [21]:
step = 2000
start = 10000
end = -10000

In [22]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [23]:
await moveHexInSteps(0, start, step)

Step size is 2000 um, 
 z positions 
 [    0  2000  4000  6000  8000 10000]


In [24]:
await moveHexInSteps(start, end, step)

Step size is -2000 um, 
 z positions 
 [ 10000   8000   6000   4000   2000      0  -2000  -4000  -6000  -8000
 -10000]


In [25]:
await moveHexInSteps(end, 0, step)

Step size is 2000 um, 
 z positions 
 [-10000  -8000  -6000  -4000  -2000      0]


In [26]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

---
## Step size 5000 um

In [21]:
step = 5000
start = 10000
end = -10000

In [22]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [23]:
await moveHexInSteps(0, start, step)

Step size is 5000 um, 
 z positions 
 [    0  5000 10000]


In [31]:
await moveHexInSteps(7800, 0, 500)

Step size is -500 um, 
 z positions 
 [7800 7300 6800 6300 5800 5300 4800 4300 3800 3300 2800 2300 1800 1300
  800  300 -200]


In [32]:
await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=0,u=0,v=0,w=0,sync=True)


In [ ]:
await moveHexInSteps(end, 0, step)

In [ ]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

In [33]:
await salobj.set_summary_state(mtcs.rem.mthexapod_1, salobj.State.STANDBY)

[<State.ENABLED: 2>, <State.DISABLED: 1>, <State.STANDBY: 5>]

---
## Step size 10000 um

In [27]:
step = 10000
start = 10000
end = -10000

In [28]:
script.log.info(f"START - {test_message} -- {step} um step size motion from {start} to {end}")

In [29]:
await moveHexInSteps(0, start, step)

Step size is 5000 um, 
 z positions 
 [    0  5000 10000]


In [ ]:
await moveHexInSteps(start, end, step)

Step size is -5000 um, 
 z positions 
 [ 10000   5000      0  -5000 -10000]


In [ ]:
await moveHexInSteps(end, 0, step)

In [ ]:
script.log.info(f"END - {test_message} -- {step} um step size motion from {start} to {end}")

In [33]:
await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=10000,u=0,v=0,w=0,sync=True)


In [34]:
await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=0,u=0,v=0,w=0,sync=True)


In [36]:
await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=-10000,u=0,v=0,w=0,sync=True)


In [37]:
await mtcs.rem.mthexapod_1.cmd_move.set_start(x=0,y=0,z=0,u=0,v=0,w=0,sync=True)


In [40]:
await salobj.set_summary_state(mtcs.rem.mthexapod_1, salobj.State.STANDBY)

[<State.ENABLED: 2>, <State.DISABLED: 1>, <State.STANDBY: 5>]